### ISSUE TITLE
Unable to copy updated database

### ISSUE THREAD

**Issue by ranjithshegde** [residentsummer/watoi#12]
Hi,
I am unable to copy the updated database back into the backup folder. Each time I run the command (with the correct path identified in earlier stages) its says no such directory found

I have copied the 7cxxxxxxxxxxxx file to desktop and then tried to do the step but terminal says the same thing

here is the terminal error message
Ranjeets-iMac:watoi hackintosh$ cp ChatStorage.sqlite “~/Library/Application Support/MobileSync/Backup/b57c35e867319d59df7a6b4d7458bc306f35b2f5/7c/7c7fba66680ef796b916b067077cc246adacf01d”
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
Ranjeets-iMac:watoi hackintosh$ 

Please help

**Comment by residentsummer** [comment]
Added a note about this to the README.
