### ISSUE TITLE
whatsapp crashes with the new file

### ISSUE THREAD

**Issue by 2600box** [residentsummer/watoi#14]
whatsapp loads and if i am quick i can see the expected history in chats. after a few seconds, whatsapp crashes.

any idea what is going wrong?

**Comment by residentsummer** [comment]
Uh, nope... Do you have any logs? iTunes used to copy them on syncronization, to be viewed in Console.app.

**Comment by residentsummer** [comment]
Feel free to reopen the issue if you got more information or steps to reproduce the crash.
