### ISSUE TITLE
 Failed to load NSManagedObjectModel with URL

### ISSUE THREAD

**Issue by TimoJansen** [residentsummer/watoi#15]
error:  Failed to load NSManagedObjectModel with URL 'app/Payload/WhatsApp.app/WhatsAppChat.momd -- file:///Users/timojansen/Downloads/watoi/'
2018-09-08 16:36:27.608 watoi[3588:485626] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Cannot create an NSPersistentStoreCoordinator with a nil model'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2c4a043d __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff582ea720 objc_exception_throw + 48
	2   CoreData                            0x00007fff2bf27a8e -[NSPersistentStoreCoordinator initWithManagedObjectModel:] + 430
	3   watoi                               0x0000000106843c71 -[Importer initializeCoreDataWithMomd:andDatabase:] + 211
	4   watoi                               0x0000000106843b44 main + 324
	5   libdyld.dylib                       0x00007fff593b70a1 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by TimoJansen** [comment]
I think the problem is is that my Android backup isn't decrypted

**Comment by residentsummer** [comment]
@TimoJansen error message says that utility can't load model descriptions from extracted application bundle. Please provide the exact command you've used to start the migration.

**Comment by residentsummer** [comment]
Some time ago I've added a check to ensure that model descriptions are loaded. Otherwise it'll print a clear (I hope :) ) error message.
