### ISSUE TITLE
Unable to open database

### ISSUE THREAD

**Issue by oecher** [residentsummer/watoi#2]
Thanks for providing this tool, @residentsummer! I'd love to move my old Android chats to my new iPhone 4S (I'm new to iOS and iPhone...) but unfortunately I'm stuck at the step "Locate Whatsapp database file inside the backup and copy it somewhere". In my Backup folder there is no Manifest.db, only a file named Manifest.mbdb. Is there something I am missing? I deleted my backup several times and created a fresh one but that didn't change anything.
As I'm also new to gitHub I'm not sure if an issue is the correct way to address my question but I hope that's okay :)
Thanks in advance!

PS. My phone's on iOS 9.3.5 and WhatsApp 2.17.42 in case that's important. iTunes is on version 12.6.2.20

**Comment by oecher** [comment]
Just a quick update in case someone reads this... I used another tool to extract the ChatStorage.sqlite from the backup. In addition I had to change the path to the file WhatsAppChat.momd (within folder "Payload" there's another folder for version 2.17.42 named "WhatsApp.app" in which the file is contained). But when I now run the program I receive the error 

xxxxx:watoi xxxxx$ build/Release/watoi /Downloads/msgstore.db /Downloads/watoi/ChatStorage.sqlite app/Payload/WhatsApp.app/WhatsAppChat.momd
2017-08-19 18:51:36.620 watoi[890:35828] unable to open database file
2017-08-19 18:51:36.620 watoi[890:35828] Android store loaded
CoreData: error: -addPersistentStoreWithType:SQLite configuration:(null) URL:file:///Downloads/watoi/ChatStorage.sqlite options:{
    NSSQLitePragmasOption =     {
        "journal_mode" = DELETE;
    };
} ... returned error Error Domain=NSCocoaErrorDomain Code=512 "The file couldn’t be saved." UserInfo={reason=Failed to create file; code = 2} with userInfo dictionary {
    reason = "Failed to create file; code = 2";
}
2017-08-19 18:51:36.730 watoi[890:35828] CoreData loaded
2017-08-19 18:51:36.730 watoi[890:35828] unable to open database file
Abort trap: 6

Any hints how to get rid of that?
Thanks and best regards

**Comment by residentsummer** [comment]
Hi, @oecher!

From your last message:

> $ build/Release/watoi /Downloads/msgstore.db /Downloads/watoi/ChatStorage.sqlite app/Payload/WhatsApp.app/WhatsAppChat.momd
2017-08-19 18:51:36.620 watoi[890:35828] unable to open database file

If this is indeed the command you've typed, than the mistake is pretty easy to fix. You've specified wrong paths to the database files. It should be like this (note the `~` in front of Downloads folder):

> $ build/Release/watoi ~/Downloads/msgstore.db ~/Downloads/watoi/ChatStorage.sqlite app/Payload/WhatsApp.app/WhatsAppChat.momd

Regarding the missing `Manifest.db` - it's a new backup format, introduced in iOS 10. Since you have an older iOS, there is an `.mbdb` file instead. But it's not a problem - just try one of the existing tools (like the one you've used to extract ChatStorage.sqlite) to replace the database file after import is done.

Hope this helps!

**Comment by oecher** [comment]
Hi, @residentsummer,

Thank you very much! This helped a lot and the migration ran successfully. Now that I’ve come so far I realised that I can’t figure out what to do to replace the old ChatStorage.sqlite in the backup with the new one...
I found two Python scripts to convert a .mbdb to a .csv and vice versa but I don’t understand where I have to put the updated ChatStorage.sqlite in order to include it in my existing backup.
Following your instructions a new folder /ab/01234567890 seems to be created within the backup (btw: where does /ab/ come from? And does the Manifest.db in your example not have to be adapted?). Do I have to create such a folder as well manually? Or do I rename my new ChatStorage.sqlite to the fileID I found for ChatStorage.sqlite in Manifest.mbdb and replace the file in the backup? That’s currently my best guess… 

Thanks and best regards!

**Comment by residentsummer** [comment]
@oecher if it's still relevant, you may try to follow [this guide](https://conath.me/2016/01/tweak-iphone-without-jailbreaking/) on modifying iOS 9 backups.

Feel free to close this issue if your problem is solved.

**Comment by oecher** [comment]
Hi, @residentsummer,

I'm sorry for not answering earlier. Thank you for the link to the guide, I'll try that once I have some time for this project again. 
I'll close this issue as obviously there's no problem with your code.
Thanks again for all your efforts you put in this!

All the best!
