### ISSUE TITLE
newbie confused

### ISSUE THREAD

**Issue by snowguardgit** [residentsummer/watoi#3]
Hi, I'm trying to switch from Android to iOS, i'm new, and after rummaging a week without success (between guide or tutorial that bring to nothing) I find this guide, and people say it works ;)
I'm not in programming, I'm good at DOS and Windows, but they are not helping me right know, and I need help to use this app.
I pass the phase of building the migration utility, not easy for me, but i think i did it right.
I locate the iphone backup, but was unable to locate whatsapp database inside backup. I don't understand this command: 
$ sqlite3 <backup>/Manifest.db "select fileID from Files where relativePath = 'ChatStorage.sqlite' and domain like '%whatsapp%';" 

I have to erase the $ to have some result, I change <backup> with the actual name of the folder (ea43yh45...) and it does something, like create some copies of manifest.db (manifest.db-shm and manifest.db-wal) but than I don't know what to do with the abcdef01234567890. I stopped here

didn't try to go to the next step... $ cp <backup>/ab/abcdef01234567890 ~/Downloads/watoi/ChatStorage.sqlite
I know it's not so easy to help someone who doesn't know the basics, a noob tutorial should be the best, and I can do it, if you want, when I know how to do this...

Thank you

Snow.

EDIT UPDATE

I use a third party software to retrive the ChatStorage.sqlite from the backup, use your commands to transform msgstore.db in ChatStorage.sqlite and try to put the new ChatStorage.sqlite of 11MB (so your software works) but was unable to restore the backup. Actually as i try to put the new file in the backup, it say, in this third party app (iBackupBot), that putting this file, the restore process will fail, and it fails...

**Comment by residentsummer** [comment]
Hi, @snowguardgit!

Please provide output of the sqlite command (substituting `<backup>` with the actual backup path):
```
sqlite3 <backup>/Manifest.db "select fileID from Files where relativePath = 'ChatStorage.sqlite' and domain like '%whatsapp%';"
```

About `abcdef01234567890` - it's just an example of how that command's output should look like. The result is a file name of whatsapp's database in the backup directory. For example, if the sqlite's output would have been `d0ab3976ddce`, your database file will be located at `<backup>/d0/d0ab3976ddce`. That is composed of the backup path + first two characters of the file name + the whole file name.

If you already extracted DB file and run the importer, than you just need to put the modified db at the location that we've determined with sqlite command in the former paragraph. Don't forget to save the original file in a safe place in case something go wrong!

**Comment by snowguardgit** [comment]
Thank you very much for your prompt answer, @residentsummer, 

I tried the sqlite3 string and it went good, a get a 7c7fba66680ef796b916b067077cc246adacf01d then next step is good too, ChatStorage.sqlite appears in the watoi folder, then extraction create an App folder, I save the ChatStorage.sqlite in a documents folder, and now the migration. 
This is the command I send:
build/Release/watoi ~/Downloads/watoi/msgstore.db ChatStorage.sqlite app/Payload/WhatsApp.app/WhatsAppChat.momd

I receive a long list of string I copy in a txt file with not found at the end
[migration.txt](https://github.com/residentsummer/watoi/files/1553447/migration.txt)
the android database is 36MB, the iOs database only 12.2MB

when I replace the database, i know how to do now (just a little problem with "), and then restore the backup, 2 things happen, 

the first iPhone ask me 3 or 4 question, to set up wifi and so on, after the iPhone start i can see the WhatsApp application with the updating icon, after a few second, ask me to put the telephone number to reactivate the app, even if prior to restore was activated, the iPhone is new, no data inside, but as you suggest I sent a message or two; 
the second is I have non of my messages but the group (without any message inside)

thank you for your time

Snow.

**Comment by residentsummer** [comment]
@snowguardgit sorry, I didn't have time to look at the issue since then. Is it still relevant?

**Comment by snowguardgit** [comment]
I was planning on writing to you, it's still relevant, but I've found a whatsapp viewer and I'm good with it atm. I would like to merge the 2 database when it will be possible, and if it is possible. No rush, no hurry, but please take a look at it whenever you can. Thanks for your guidance and happy holidays!

**Comment by ranjithshegde** [comment]
Greetings,
I am having trouble with copying the updated file back into the backup folder. Each time I type the command in the terminal it says no such directory found. Please help

**Comment by residentsummer** [comment]
cleanup
