### ISSUE TITLE
Only Group Messages are imported

### ISSUE THREAD

**Issue by Th-Os** [residentsummer/watoi#34]
Hello,

at first I would like to thank you all for this cool tool!
I followed the README and went through the process relatively fast. However, as soon as I restored the backup with the Apple Configurator 2, I only see the messages of group chats. The "individual" chats are not included.

Do you have a guess on why this could be happening?

Systems:
iPhone 6s
iOS 14.2
macOS Catalina

**Comment by residentsummer** [comment]
Hi, @Th-Os ! Have no idea why this might be... I've seen some reports that chats sometimes end up in archive, could you please check there?

Do you have the logs of the tool doing migration?

**Comment by RahulSriram** [comment]
Had the same issue, found all my personal chats in archive

**Comment by Th-Os** [comment]
You are right!
This would be something for the Troubleshooting section.

Thank you both!
