### ISSUE TITLE
How to get an unencrypted message database from Android?

### ISSUE THREAD

**Issue by johnneuland** [residentsummer/watoi#36]
Where can I find this? Is it in some folder in my phone or do I need to obtain it using some programming commands?

The instructions say "Create an unencrypted backup to local computer (not iCloud) with iTunes." Could you please also elaborate on how I can transfer from my android to my computer using iTunes? Can't I just use a data transfer cable and copy paste? If so, where exactly do I paste?

**Comment by MaxWolodin** [comment]
Have a look at issue #35

**Comment by residentsummer** [comment]
cleanup
