### ISSUE TITLE
Boot loop after restoring

### ISSUE THREAD

**Issue by gch1p** [residentsummer/watoi#37]
Hi! Just followed the instructions, did not modify anything like in [this issue](https://github.com/residentsummer/watoi/issues/33), and here it is, the boot loop. Any ideas what could go wrong?

My device is iPhone 8, iOS 14.3.

**Comment by residentsummer** [comment]
Please take a look at the suggestions in the last messages of #29 (trying different IPAs). I'm not sure how the contents of whatsapp DB can lead a boot loop, though. I believe something else cause this and fix by using different IPA is just a coincidence...

Anyway, let us continue in the mentioned issue. Please leave a comment there whether changing an IPA helped you or not.

**Comment by gch1p** [comment]
Ah, sorry. Somehow I did not see that issue. It even has the same title as mine! :D

**Comment by residentsummer** [comment]
@gch1p I've changed the title as your variant are easier to find :)
