### ISSUE TITLE
bedit.sh operation not permitted

### ISSUE THREAD

**Issue by uzairahmadch** [residentsummer/watoi#46]
<img width="591" alt="Screen Shot 2021-08-14 at 12 33 59 AM" src="https://user-images.githubusercontent.com/7118606/129409903-0c4d7fba-f5ae-48cb-b8f4-b7302de341d5.png">

**Comment by greeningFLY** [comment]
https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
got stuck on there too

**Comment by residentsummer** [comment]
Thanks, @greeningFLY ! Added note about that to readme.

**Comment by uzairahmadch** [comment]
thanks for this, I'll look into it.

> https://osxdaily.com/2018/10/09/fix-operation-not-permitted-terminal-error-macos/
> got stuck on there too
