### ISSUE TITLE
trying to make a simple whatsapp filter.

### ISSUE THREAD

**Issue by noni2724** [residentsummer/watoi#49]
hello brother sorry if i posted this here but i had no info of you to contact you anyhow. i am trying to make a simple whatsapp filter and i came across an old code which was like https://v.whatsapp.net/v/code?=+919xxxxx something like this and if the result comes ok then the number is on whatsapp if it comes as other then its not. problem is that since the api was changed by whatsapp long time ago the new server wasnt known. but it seems now its https://pps.whatsapp.net/ something like this. please let me know if you can help me out.

**Comment by residentsummer** [comment]
Hi, @noni2724 ! Sorry, I'm not aware of any service providing this info...
