### ISSUE TITLE
Need help with migration

### ISSUE THREAD

**Issue by MaxAchtermann** [residentsummer/watoi#55]
Hello. For the most part I've been using @needs-coffe tutorial on how to do it on a virtual machine.

Now the problem is, this migration command:
`watoi/build/Release/watoi ./msgstore.db ./ChatStorage.sqlite app/Payload/WhatsApp.app/Frameworks/Core.framework/WhatsAppChat.momd`

It outputs me this:
`Natnaels-Mac:WhatsApp-Migration natnael$ watoi/build/Release/watoi ./msgstore.db ./ChatStorage.sqlite app/Payload/WhatsApp.app/Frameworks/Core.framework/WhatsAppChat.momd
2022-02-12 19:36:59.970 watoi[1660:50816] Probing msgstore.db at path: ./msgstore.db
2022-02-12 19:36:59.996 watoi[1660:50816]     ok.
2022-02-12 19:36:59.998 watoi[1660:50816] Android store loaded
2022-02-12 19:36:59.998 watoi[1660:50816] Probing WhatsAppChat.momd at path: app/Payload/WhatsApp.app/Frameworks/Core.framework/WhatsAppChat.momd
2022-02-12 19:37:00.014 watoi[1660:50816]     missing/not a dir!
Abort trap: 6`

Sadly I have no idea what to do or what this even means, so help would be appriciated.

**Comment by MaxAchtermann** [comment]
found a workaround

you have to unzip the .ipa file manually

(you need to rename "Whatsapp.ipa" to "Whatsapp​.zip", then unzip it and continue with the guide)

**Comment by chikko80** [comment]
@MaxAchtermann Where did you get the ipa file?

**Comment by MaxAchtermann** [comment]
@chikko80 I followed these steps from @needs-coffe tutorial:
### _Step 4 - Get a copy of the WhatsApp.ipa file_
You will need a copy of WhatsApp.ipa of same version you have on your device. You can get this from the internet or following [this guide](https://dev.to/tranthanhvu/how-to-download-ipa-file-from-appstore-37im) to obtain via Apple Configurator 2, the steps of which are summarised below.

1. Update WhatsApp on the iPhone
2. Install and open Apple Configurator 2 (AC2)
3. Connect your phone
4. Right click on the phone in the AC2 window and click add > apps > WhatsApp
5. When prompted that WhatsApp already exists don't click anything and open finder
6. Copy the ipa file from ~/Library/Group Containers/K36BKF7T3D.group.com.apple.configurator/Library/Caches/Assets/TemporaryItems/MobileApps/ to your working directory
7. Cancel the previous prompts and close AC2

[https://github.com/needs-coffee/Whatsapp-android-to-ios-guide/blob/main/README.md#step-4---get-a-copy-of-the-whatsappipa-file](url)
